name: "Doom Example"
description: "An example pipeline that lets you play Doom on Buildkite, optionally with Claude Code."
emoji: ":rage4:"
languages:
  - Ruby
steps:
  - label: ":pipeline:"
    command: "buildkite-agent pipeline upload"
